#rover:
#  send:
#    device : "rover"
#    serial_port : "/dev/ttyAMA2"
#    baudrate : 460800
#    timeout : 3
#    daemon : True
#    mode : "send"
#
#  test:
#    device : "rover"
#    serial_port : "/dev/ttyAMA2"
#    baudrate : 460800
#    timeout : 3
#    daemon : True
#    mode : "test"



base:
  send: 
    device : "base"
    serial_port : "COM4"
    baudrate : 460800
    timeout : 3
    daemon : True

  test:
    device : "base"
    serial_port : "COM4"
    baudrate : 460800
    timeout : 3
    daemon : True


  

